* Added cookbook for downlink between servers
swimos/cookbook pull request #10
Opened 2021-09-30 12:47 UTC by PiggottDev

Added a cookbook where a downlink is used between two servers.

A JoinMapLane is also created where the downlinks are on a separate server.

2021-09-30 14:39 UTC, DobromirM requested changes
Looks good overall, but it might need to be simplified a bit because the `JoinMapLane` is adding some additional complexity.

2021-09-30 14:39 UTC, DobromirM commented on server_downlinks/src/main/java/swim/basic/BasicPlane.java
> +                .open();
The did update method for the `JoinMapLane` can be moved to the lane itself in the `SupplierAgent`.

2021-09-30 14:39 UTC, DobromirM commented on server_downlinks/src/main/java/swim/basic/CustomPlane.java
> +        context.command("/warehouse/cambridge", "addItem", Text.from("foo"));
Maybe add more warehouse endpoints.

2021-10-01 04:53 UTC, ajay-gov commented
Will be good to showcase these 4 scenarios

- Downlink to a `ValueLane` in plane 1 from plane 2 using the  plane 2's context
- Downlink to a `MapLane` in plane 1 from plane 2 using the  plane 2's context
- Downlink to a `ValueLane` in plane 1 from an agent in plane 2 using the agent's context
- Downlink to a `MapLane` in plane 1 from an agent in plane 2 using the agent's context

2021-10-01 13:38 UTC, PiggottDev commented
Resolved all of Dobromir's comments and added each scenario mentioned by Ajay

2021-10-01 15:15 UTC, ajay-gov commented
@PiggottDev looks good! Couple of minor fixes and then it should be good to merge. 

It's hard to see where the log messages for the downlink callbacks are getting invoked i.e from the Plane or from the Agent. It might be good to make that explicit in the log messages. In general I think it is good to prefix the `nodeUri()` in the Agent log messages. So something like: `System.out.println(nodeUri() + ": .....")`

The Readme title still says JoinLanes,

2021-10-01 15:59 UTC, PiggottDev commented
@ajay-gov Thanks - I've made the logging better and fixed the Readme title

2021-10-02 00:45 UTC, ajay-gov commented
I'm ok if this gets merged into master if @DobromirM approves

2021-10-04 09:47 UTC, DobromirM approved these changes

2021-10-06 16:37 UTC, merged