Static Traits Cookbook
swimos/cookbook pull request #26
Opened 2022-03-08 02:36 UTC by AdityaRandive

This commit introduces a cookbook to illustrate Static Traits.

Author: Aditya R
Reviewers: Ajay G, Rohit B
Test: Manual
Issue: https://github.com/swimos/cookbook/issues/24

2022-03-08 07:57 UTC, ajay-gov requested changes
The static trait definitions look good. Couple of comments

- [x]  With the way the agents are defined, there will be one agent with uri as '/liquid' which will have both the `WaterAgent` and `JuiceAgent`. This is ok from a code perspective but a bit confusing . It might be better to have 3 agent classes `LiquitdAgent`, `WaterAgent` and `JuiceAgent`. Then you can have 2 node definitions in the recon file- `/water` which has both the `LiquidAgent` and the `WaterAgent`, `/oj ` which has the the `LiquidAgent` and the `JuiceAgent`. That is just one idea.
- [x]  Also the reading of the props from the recon file may be overkill for this specific cookbook. You could just have the property in the recon file .

2022-03-09 03:29 UTC, ajay-gov requested changes
Looks good, couple of things

- [x]  Maybe make the uris specific, since it is sparkling water the uri could be `/water/sparkling` and since it is orange juice the uri could be `/juice/orange`?
- [x]  You can just have one lane called `info` instead of having two lanes `sharedWaterInfo` and `sharedJuiceInfo` in the `LiquidAgent`. The `WaterAgent` and the `JuiceAgent` will have just one lane i.e `info` 
- [ ]  Also it might be best to remove the chinese readme file

2022-03-10 04:25 UTC, ajay-gov approved these changes

2022-03-10 05:06 UTC, brohitbrose approved these changes
I like it. It's a very efficient way of showing how traits can be composed with shared or unshared properties.

2022-03-10 08:37 UTC, merged