Dynamic Traits Cookbook
swimos/cookbook pull request #28
Opened 2022-03-11 00:00 UTC by AdityaRandive

This commit illusrates Dynamic Traits w.r.t. the Agents, respective properties
and the shared lanes.

Author: Aditya R
Reviewers: Ajay G, Rohit B
Test: Manual
Issue: https://github.com/swimos/cookbook/issues/24

2022-03-11 05:26 UTC, ajay-gov requested changes
The dynamic traits look good from a code perspective. Couple of suggestions

- [ ]  It might good to have the logic of determining what trait to load based on the data passed into a lane, say `config`.  You could call that with `space.command` and the payload can be a `Value` with a `type` key which may be "Water" or "Juice" . The callback function on the `config` lane could load the appropriate trait based on the value of the `type`. That way you can remove the props in the recon file for `/liquid/:id`

- [ ]  Just the `sharedInfo` lane should be fine, not sure we need another `shared lane?

- [ ]  Minor thing, maybe use proper agent names instead of random ints as ids. `/liquid/distilled, `/liquid/apple` say. Also it might be best to have `/liquid/sparkling` and `/liquid/orange` for the static traits to be consistent. What do you think?

2022-03-11 05:31 UTC, brohitbrose requested changes
- [ ] Checkstyle fixes
- [x] LiquidAgent.java: `didStart` logs the word "region", which doesn't make sense for this app -- I'm guessing this is an artifact from cellular

2022-03-16 23:03 UTC, brohitbrose reviewed
Looks good other than the aforementioned comment.

2022-03-17 07:14 UTC, ajay-gov commented
@AdityaRandive The general pattern would be for the traits (i.e. `Juice` or `Water` to have logic that sets the shared lane which then gets reflected in the base agent i.e `Liquid`. So I think it will be good to move the calls to set the lanes to the `Juice` and `Water` agents.

Also having two lanes, one for sharing info of static traits and one for sharing info of dynamic traits, is a bit confusing. The main idea here is to show that you can have the same lane and use it across static and dynamic traits and share "info". That way downstream clients that access data from these agents can just subscribe to one lane i.e `sharedInfo` lane. Otherwise they will have to subscribe to two lanes which seems a bit more tedious.

2022-03-17 20:25 UTC, AdityaRandive commented
> @AdityaRandive The general pattern would be for the traits (i.e. `Juice` or `Water` to have logic that sets the shared lane which then gets reflected in the base agent i.e `Liquid`. So I think it will be good to move the calls to set the lanes to the `Juice` and `Water` agents.
> 
> Also having two lanes, one for sharing info of static traits and one for sharing info of dynamic traits, is a bit confusing. The main idea here is to show that you can have the same lane and use it across static and dynamic traits and share "info". That way downstream clients that access data from these agents can just subscribe to one lane i.e `sharedInfo` lane. Otherwise they will have to subscribe to two lanes which seems a bit more tedious.

ACK

2022-03-21 23:41 UTC, brohitbrose approved these changes

2022-03-22 00:23 UTC, ajay-gov approved these changes

2022-03-22 03:21 UTC, merged